### ISSUE TITLE
Wercker should have a new homepage

### ISSUE THREAD

**Issue by lindseybateman** [wercker/wercker-corporate#13]
#### ToDo
- [x] Menu bar
- [x] Header
- [x] Interactive getting started
- [x] Make terminal dynamic
- [x] Usp's
- [x] Customer feedback, with carrousel 
- [x] Toolchain
- [x] Codeblock
- [x] Footer
